<?php
# PHPlot Example: Bar chart, with data labels
//require_once 'phplot.php';
require_once '../plot/phpplot/phplot.php';

require_once("../class/session.php");
require_once '../class/conexao.class.php';

require_once("../class/class.user.php");

include '../bootstrap.php';



//$principal = '../principal/principal_config.php';


$auth_user = new USER();

$mpdf = new mPDF();

//Verificação da Sessao
$user_id = $_SESSION['user_session'];
$stmt = $auth_user->runQuery("SELECT * FROM funcionarios WHERE funcionario_id=:user_id");
$stmt->execute(array(":user_id" => $user_id));
$userRow = $stmt->fetch(PDO::FETCH_ASSOC);



$busca_cliente_mun = $auth_user->runQuery("SELECT municipio.municipio_sigla AS Estado,
   COUNT(*) AS Clientes
FROM municipio, cliente WHERE id_municipio = municipio_id 
GROUP BY municipio.municipio_sigla
 ORDER BY COUNT(*) DESC;");
$busca_cliente_mun->execute();




while ($row = $busca_cliente_mun->fetch(PDO::FETCH_ASSOC)) {
$data[] = array($row['Estado'], $row['Clientes']);

//  array('China', 1306.31),          
//  array('India', 1080.26),
//  array('United States',  295.73),  
//  array('Indonesia', 241.97),
//  array('Brazil', 186.11),  
//  array('Pakistan', 162.42),
//  array('Bangladesh', 144.32),  
//  array('Russia', 143.42),
    
} 

# This global string accumulates the image map AREA tags.
$image_map = "";

# Data for bar chart:
//$data = array(
//    array('1980', 13, 21,  8, 24, 10, 19),
//    array('1990', 14, 19,  6, 26, 11, 13),
//    array('2000', 11, 13,  8, 15,  9, 11),
//    array('2010', 13, 16,  9, 21, 12, 13),
//);
$legend = array('Estado');

# Produce an image if the URL has mode=plot, and an HTML page otherwise:
$do_html = empty($_GET['mode']) || $_GET['mode'] != 'plot';

# Callback for 'data_points' : Generate 1 line in the image map.
function store_map($im, $data, $shape, $row, $col, $x1, $y1, $x2, $y2)
{
  global $image_map;
  if ($shape != 'rect') die("Error expecting rect shapes from plot\n");
  # Get the data point value. (Offset column by 1 to skip label)
  $value = $data[$row][$col+1];
  # See top note: URL for demonstration purposes.
  $message = "Data value: $value";
  $url = "javascript:alert('$message')";
  # Convert coords to integers:
  $coords = sprintf("%d,%d,%d,%d", $x1, $y1, $x2, $y2);
  # Area alt text (required attribute):
  $alt = "Region for Group $row bar $col";
  # Area title text, which is displayed as the tool-tip:
  $title = "Group $row bar $col";

  # Append one line to the image map:
  $image_map .= "  <area shape=\"rect\" coords=\"$coords\""
             .  " title=\"$title\" alt=\"$alt\" href=\"$url\">\n";
}

# Produce an HTML page which includes the image map and the reference
# to the plot image. The plot image is generated by this same script,
# with a mode=plot URL parameter.
function generate_html()
{
    global $image_map;

    # Self-referencing URL for <img>, with additional mode=plot parameter.
    # If the URL already has parameters, use & separator, else ?.
    $sep = empty($_SERVER['QUERY_STRING']) ? '?' : '&';
    $url = htmlspecialchars($_SERVER['REQUEST_URI'] . $sep .  'mode=plot');
    //require_once '../pagina/menu.php';
    
require_once 'cliente_config.php';
require_once '../pagina/menu.php';
    echo <<<END


<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try {
                    ace.settings.check('breadcrumbs', 'fixed')
                } catch (e) {
                }
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="../principal/index.php">Home</a>
                </li>
                <li class="active">Cliente</li>
            </ul><!-- /.breadcrumb -->


        </div>

        <div class="page-content">
            <?php
                require_once '../principal/principal_config.php';
            ?>
            <div class="row">
                <div class="col-xs-12">



<map name="map1">
$image_map
</map>

<img src="$url" alt="Plot image" usemap="#map1">
                </div>
            </div>
        </div>
    </div><!-- /.main-content -->
</div>



END;
    
    
    
    require_once '../pagina/footer.php';
    
   
}


$plot = new PHPlot(800, 480);
if ($do_html) {
    # When producing HTML, don't output the plot image:
    $plot->SetPrintImage(False);
    # Just to make it clear, this script usage returns HTML:
    header("Content-type: text/html");
    # The image map callback is only needed when doing the HTML page.
    # Pass the data array so the callback can fetch values from it.
    $plot->SetCallback('data_points', 'store_map', $data);
}
$plot->SetTitle("Quantidade de Clientes por Estado");
$plot->SetImageBorderType('plain');
$plot->SetDataValues($data);
$plot->SetDataType('text-data');
$plot->SetPlotType('bars');
$plot->SetXTickPos('none');
$plot->SetPlotAreaWorld(NULL, 0, NULL, 30);
$plot->SetLegend($legend);
$plot->SetOutputFile('testeImagem.png');
$plot->DrawGraph();

// imagejpeg("$image","C:/Users/joildo/Desktop/teste.jpg","75");
 //imagejpeg($image, $image_map, $quality)


if ($do_html) generate_html();





